site_name: Bible Atlas Test
site_url: https://treebible.github.io/bible-atlas/
use_directory_urls: true
theme:
  name: mkdocs
extra_css:
  - mermaid-mod.css
extra_javascript:
  - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js
  - mermaid-mod.js
plugins:
  - search
  - mermaid2
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "TreeBible - Bible Atlas"
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.extra
